// <auto-generated />
namespace Lab3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initial23baranje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial23baranje));
        
        string IMigrationMetadata.Id
        {
            get { return "202405281554167_initial23baranje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
